
/* TABELA DE RECEITAS POR TIPO E CÓDIGO - COMPLETA */
SELECT 'Contribuição Social' AS 'TIPO', 'BL GBF / IGD BOLSA FAMILIA' AS 'DESCRIÇÃO', '1718041113' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL GBF / IGD BOLSA FAMILIA' AS 'DESCRIÇÃO', '1718121013' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSB / PBF / CRAS' AS 'DESCRIÇÃO', '1718121003' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSB / PBV / SCFV' AS 'DESCRIÇÃO', '1718041104' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSB / PBV / SCFV' AS 'DESCRIÇÃO', '1718121004' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PAC I' AS 'DESCRIÇÃO', '1718041106' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PAC I' AS 'DESCRIÇÃO', '1718121006' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PAC I - CRIANÇAS / ADOLESCENTES' AS 'DESCRIÇÃO', '1718041105' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PAC I - CRIANÇAS / ADOLESCENTES' AS 'DESCRIÇÃO', '1718121005' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMC / ABORDAGEM' AS 'DESCRIÇÃO', '1718041111' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMC / ABORDAGEM' AS 'DESCRIÇÃO', '1718121011' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMC / CREAS' AS 'DESCRIÇÃO', '1718041109' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMC / CREAS' AS 'DESCRIÇÃO', '1718121009' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMC / MEDIDA SOCIO EDUCATIVA' AS 'DESCRIÇÃO', '1718041112' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMC / MEDIDA SOCIO EDUCATIVA' AS 'DESCRIÇÃO', '1718121012' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMCC / CENTRO POP' AS 'DESCRIÇÃO', '1718041110' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PFMCC / CENTRO POP' AS 'DESCRIÇÃO', '1718121010' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PTMC / PISO TRANSITORIO' AS 'DESCRIÇÃO', '1718041108' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / PTMC / PISO TRANSITORIO' AS 'DESCRIÇÃO', '1718121008' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'BL PSE MAC / SIGTV' AS 'DESCRIÇÃO', '1718121018' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'CPSSS do Servidor Civil - Pensionistas - Principal' AS 'DESCRIÇÃO', '1218013100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'CPSSS do Servidor Civil Ativo - Multas e Juros de Mora' AS 'DESCRIÇÃO', '1218011200' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'CPSSS do Servidor Civil Ativo - Principal' AS 'DESCRIÇÃO', '1218011100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'CPSSS do Servidor Civil Inativo - Principal' AS 'DESCRIÇÃO', '1218012100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'CPSSS Patronal - Servidor Civil Ativo - Multas e Juros de Mora' AS 'DESCRIÇÃO', '1218031200' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'CPSSS Patronal - Servidor Civil Ativo - Principal' AS 'DESCRIÇÃO', '1218031100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'Demais Contribuições Sociais - Principal' AS 'DESCRIÇÃO', '1219991100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'FEAS -  PROTEÇÃO SOCIAL BASICA' AS 'DESCRIÇÃO', '1728991105' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'FEAS - PROTEÇÃO SOCIAL ESPECIAL' AS 'DESCRIÇÃO', '1728991106' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'Intra - Contrib.em Regime de Parcelamento de Débitos' AS 'DESCRIÇÃO', '1218021100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'OUTRAS TRANFERENCIAS DO FNAS' AS 'DESCRIÇÃO', '1718121015' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'Outras Transferências de Instituições Privadas com Fins Lucrativos - P' AS 'DESCRIÇÃO', '1740001104' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'Outras Transferências de Instituições Privadas sem Fins Lucrativos - P' AS 'DESCRIÇÃO', '1740001102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'OUTROS REPASSES DO ESTADO' AS 'DESCRIÇÃO', '1728991107' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'PISO VARIAVEL (PETI)' AS 'DESCRIÇÃO', '1718121007' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'PROGRAMA / AEPETI' AS 'DESCRIÇÃO', '1718121002' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIO FONTE 19 - FNAS PRIM. INF. SUAS' AS 'DESCRIÇÃO', '1321001104' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIOS FONTE 19 - FNAS MAC' AS 'DESCRIÇÃO', '1321001151' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIOS FONTE 19 - FNAS PSEAC' AS 'DESCRIÇÃO', '1321001117' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIOS FONTE 19 - FNAS PSEMC' AS 'DESCRIÇÃO', '1321001118' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIOS FONTE 19 - OUTRAS' AS 'DESCRIÇÃO', '1321001122' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 19 - FNAS BPC ESCOLA' AS 'DESCRIÇÃO', '1321001120' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 19 - FNAS GBF' AS 'DESCRIÇÃO', '1321001116' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 19 - FNAS GSUAS' AS 'DESCRIÇÃO', '1321001121' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 19 - FNAS PETI' AS 'DESCRIÇÃO', '1321001119' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 19 - FNAS PSB' AS 'DESCRIÇÃO', '1321001115' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 19 - FNAS PSE MAC' AS 'DESCRIÇÃO', '1321001144' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 20 - FMDCA' AS 'DESCRIÇÃO', '1321001130' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Contribuição Social' AS 'TIPO', 'TRANSFERENCIAS DE PESSOAS FISICAS AO FMDCA' AS 'DESCRIÇÃO', '1770001100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'CEU - PEC 3000 (CONTR. 0363471-63)' AS 'DESCRIÇÃO', '1718109129' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'CONST. QUADRAS A. DA PRATA, MARAMBAIA E V. DAS PEDRAS (CONTR. 1004846-' AS 'DESCRIÇÃO', '1718109127' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'CONSTR. PRAÇA EM SAMBAETIBA(CONTR. 1010439-82)' AS 'DESCRIÇÃO', '1718109128' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Contrato Repasse nº1021180-19 - Ampliação de Unidade de Atenção Especializada em Saúde -  PSI' AS 'DESCRIÇÃO', '2418101101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênio - Estruturação da Rede de Serviços de Atenção Especializada em Saúde' AS 'DESCRIÇÃO', '2418101001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Ações Regularização Fundiária, Assentamentos e Politicas Sociais' AS 'DESCRIÇÃO', '2418109107' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Construção de Áreas de Lazer e Bens Públicos' AS 'DESCRIÇÃO', '2418109103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Construção de Unidades Habitacionais' AS 'DESCRIÇÃO', '2418109108' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Equipamentos par o CEAM' AS 'DESCRIÇÃO', '2418109109' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Idade Ativa' AS 'DESCRIÇÃO', '1718109182' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Limpeza e Rec. 1° Túnel Ferroviário do Brasil' AS 'DESCRIÇÃO', '2418109104' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Pavimentação e Drenagem' AS 'DESCRIÇÃO', '2418109101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'Convênios - Restauração de Prédios Históricos' AS 'DESCRIÇÃO', '2418109102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'DIVERSITA (CONTR. 835747/2016)' AS 'DESCRIÇÃO', '1718109146' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'EQUIPAMENTOS E VEICULOS PARA O CEAM (CONV. 15/2018)' AS 'DESCRIÇÃO', '1718103108' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO E DRENAGEM NO BAIRROJARDIM QUISSAMA (CONTR. 1005351-49)' AS 'DESCRIÇÃO', '1718109103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO ALDEIA DAPRATA (CONTR. 1025326-64)' AS 'DESCRIÇÃO', '1718109112' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO AMPLIAÇÃO(CONTR. 1025217-50)' AS 'DESCRIÇÃO', '1718109101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO CHIC E MEUSOSSEGO (CONTR. 1005815-01)' AS 'DESCRIÇÃO', '1718109102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO COLONIA- ITAMBI (CONTR. 1025216-34)' AS 'DESCRIÇÃO', '1718109111' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO ENGENHOVELHO (CONTR. 1025215-19)' AS 'DESCRIÇÃO', '1718109110' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO ESPERANÇA- RETA (CONTR. 1024801-30)' AS 'DESCRIÇÃO', '1718109109' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO JOAQUIM DE OLIVEIRA (CONTR. 1035335-78)' AS 'DESCRIÇÃO', '1718109114' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NO BAIRRO RIO VARZEA(CONTR. 1025817-82)' AS 'DESCRIÇÃO', '1718109113' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PAVIMENTAÇÃO NOS BAIRROS A. DA PRATA E HELIANOPOLIS (CONTR. 1029087-24' AS 'DESCRIÇÃO', '1718109116' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'PRAÇA DA FEIRA (CONTR. 1026063-83)' AS 'DESCRIÇÃO', '1718109131' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITO BANCARIO FONTE 18 - CONVENIO' AS 'DESCRIÇÃO', '1321001139' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'CONVENIOS' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIOS FONTE 04 - CONVENIO' AS 'DESCRIÇÃO', '1321001137' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COSIP' AS 'TIPO', 'Contribuição para o Custeio do Serviço de Iluminação Pública - Princip' AS 'DESCRIÇÃO', '1240001100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COVID' AS 'TIPO', 'ADO LC 176/2020 (ADO 25)' AS 'DESCRIÇÃO', '1718991106' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COVID' AS 'TIPO', 'AFM - AUXÍLIO FINANCEIRO AOMUNICÍPIO' AS 'DESCRIÇÃO', '1718991101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COVID' AS 'TIPO', 'Outras Transferências da União - inciso I, art. 5º da LC 173/2020' AS 'DESCRIÇÃO', '1718991103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COVID' AS 'TIPO', 'Remuneração de Depósitos Bancários - FONTE 48' AS 'DESCRIÇÃO', '1321001152' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COVID' AS 'TIPO', 'Transferência de Recursos do FES/SUS (COVID-19)' AS 'DESCRIÇÃO', '1728991108' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COVID' AS 'TIPO', 'Transferência de Recursos do FNS/SUS (COVID-19)' AS 'DESCRIÇÃO', '1718039100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'COVID' AS 'TIPO', 'TRANSFERENCIAS DE RECURSOS DO  FNAS/SUAS (COVID - 19)' AS 'DESCRIÇÃO', '1718121017' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'ATUALIZAÇÃO MONETARIA IPTUAJUIZADO' AS 'DESCRIÇÃO', '1118011403' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'ATUALIZAÇÃO MONETARIA IPTUNÃO AJUIZADO' AS 'DESCRIÇÃO', '1118011404' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'ATUALIZAÇÃO MONETARIA ISSAJUIZADO' AS 'DESCRIÇÃO', '1118023403' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'ATUALIZAÇÃO MONETARIA ISSNÃO AJUIZADO' AS 'DESCRIÇÃO', '1118023404' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Dívida Ativa - COSIP - Ajuizada' AS 'DESCRIÇÃO', '1240001302' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Dívida Ativa - COSIP - Não Ajuizada' AS 'DESCRIÇÃO', '1240001301' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA FISC. VIGIL. SANITARIAAJUIZADA' AS 'DESCRIÇÃO', '1121011302' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA IPTU AJUIZADA' AS 'DESCRIÇÃO', '1118011302' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA IPTU NÃO AJUIZADA' AS 'DESCRIÇÃO', '1118011301' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA ISS AJUIZADA' AS 'DESCRIÇÃO', '1118023302' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA ISS NÃO AJUIZADA' AS 'DESCRIÇÃO', '1118023301' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA LICENÇA AMBIENTALAJUIZADA' AS 'DESCRIÇÃO', '1121041302' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA LICENÇA AMBIENTALNÃO AJUIZADO' AS 'DESCRIÇÃO', '1121041301' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA OCUPAÇÃO SOLOAJUIZADO' AS 'DESCRIÇÃO', '1121011306' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA OUTRAS TAXASAJUIZADA' AS 'DESCRIÇÃO', '1121011310' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA OUTRAS TAXASNÃO AJUIZADA' AS 'DESCRIÇÃO', '1121011309' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA PUBLICIDADEAJUIZADO' AS 'DESCRIÇÃO', '1121011308' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA ATIVA PUBLICIDADENÃO AJUIZADO' AS 'DESCRIÇÃO', '1121011307' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA TFIF AJUIZADO' AS 'DESCRIÇÃO', '1121011304' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DIVIDA TFIF NÃO AJUIZADO' AS 'DESCRIÇÃO', '1121011303' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'DVIDA ATIVA FISC. VIGIL. SANITARIANÃO AJUIZADA' AS 'DESCRIÇÃO', '1121011301' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'MULTAS, JUROS DE MORA E DIVIDAATIVA IPTU AJUIZADA' AS 'DESCRIÇÃO', '1118011401' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'MULTAS, JUROS DE MORA, DIVIDAATIVA IPTU NÃO AJUIZADA' AS 'DESCRIÇÃO', '1118011402' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'MULTAS, JUROS DE MORA, DIVIDAATIVA ISS AJUIZADA' AS 'DESCRIÇÃO', '1118023401' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'MULTAS, JUROS DE MORA, DIVIDAATIVA ISS NÃO AJUIZADA' AS 'DESCRIÇÃO', '1118023402' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'MULTAS, JUROS DE MORA, DIVIDAATIVA TAXAS AJUIZADAS' AS 'DESCRIÇÃO', '1121011401' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'MULTAS, JUROS DE MORA, DIVIDAATIVA TAXAS NÃO AJUIZADAS' AS 'DESCRIÇÃO', '1121011402' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'OUTRAS DIVIDAS ATIVAS' AS 'DESCRIÇÃO', '1121011311' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços de Coleta de Resíduos Sólidos - AJUIZADO' AS 'DESCRIÇÃO', '1122011302' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços de Coleta de Resíduos Sólidos - Dívida Ativa N/AJUIZADA' AS 'DESCRIÇÃO', '1122011301' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços de Limpeza Pública - AJUIZADO' AS 'DESCRIÇÃO', '1122011304' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços de Limpeza Pública - N/AJUIZADO' AS 'DESCRIÇÃO', '1122011303' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços de Manutenção Rede Esgoto - AJUIZADO' AS 'DESCRIÇÃO', '1122011306' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços de Manutenção Rede Esgoto - N/AJUIZADO' AS 'DESCRIÇÃO', '1122011305' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços Urbanos - AJUIZADO' AS 'DESCRIÇÃO', '1122011308' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxa pela Prestação de Serviços Urbanos - N/AJUIZADO' AS 'DESCRIÇÃO', '1122011307' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'DIVIDA ATIVA' AS 'TIPO', 'Taxas pela Prestação de Serviços -Dívida Ativa - Multas e Juros' AS 'DESCRIÇÃO', '1122011400' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Cota-Parte do Fundo de Participação do Municípios – 1% alinea "d" dezembro' AS 'DESCRIÇÃO', '1718013100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Cota-Parte do Fundo de Participação dos Municípios - 1% alinea "e" Julho' AS 'DESCRIÇÃO', '1718014100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'EDUCAÇÃO INFANTIL' AS 'DESCRIÇÃO', '1718059112' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'FNDE AUXILIO MP 815/2017' AS 'DESCRIÇÃO', '1718059114' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Outras Transferências Diretas do Fundo Nacional do Desenvolvimento da Educação – FNDE' AS 'DESCRIÇÃO', '1718059199' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'PMI ITABORAI - PAC (T.C. 11110)' AS 'DESCRIÇÃO', '1718059108' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'PMI ITABORAI - PAR (T.C. 00019)' AS 'DESCRIÇÃO', '1718059106' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'PMI ITABORAI - PAR (T.C. 31337)' AS 'DESCRIÇÃO', '1718059103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'PROGRAMA / BPC NA ESCOLA' AS 'DESCRIÇÃO', '1718121001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'PROGRAMA BRASIL CARINHOSO' AS 'DESCRIÇÃO', '1718059111' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'PROGRAMA CAMINHO DA ESCOLA' AS 'DESCRIÇÃO', '1718059102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS - FONTE 55' AS 'DESCRIÇÃO', '1321001159' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS - FONTE 56' AS 'DESCRIÇÃO', '1321001160' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS - FONTE 57' AS 'DESCRIÇÃO', '1321001161' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS - FONTE 58' AS 'DESCRIÇÃO', '1321001162' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS - FUNDEB' AS 'DESCRIÇÃO', '1321001103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 07 - SAL. EDUCAÇÃO' AS 'DESCRIÇÃO', '1321001128' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 11 - TESOURO VINC EDUCAÇÃO' AS 'DESCRIÇÃO', '1321001143' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 15 - PNAE' AS 'DESCRIÇÃO', '1321001131' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 16 - PNATE' AS 'DESCRIÇÃO', '1321001113' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 24 - OUTRAS TRANSF. FNDE' AS 'DESCRIÇÃO', '1321001132' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transf de Recursos de Complementação da União ao FUNDEB - VAAF (30%)' AS 'DESCRIÇÃO', '1718991112' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transf de Recursos de Complementação da União ao FUNDEB - VAAF (70%)' AS 'DESCRIÇÃO', '1718991111' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transf de Recursos de Complementação da União ao FUNDEB - VAAT (30%)' AS 'DESCRIÇÃO', '1718991114' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transf de Recursos de Complementação da União ao FUNDEB - VAAT (70%)' AS 'DESCRIÇÃO', '1718991113' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'TRANSFERENCIA FNDE AQ. MOBILIARIA(T.C. 01586 E 05920)' AS 'DESCRIÇÃO', '1718059101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transferências de Recursos da Complementação da União ao Fundo de Manu' AS 'DESCRIÇÃO', '1758012100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transferências de Recursos do Fundo de Manutenção e Desenvolvimento da' AS 'DESCRIÇÃO', '1758011100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transferências Diretas do FNDE referentes ao Programa Nacional de Alim' AS 'DESCRIÇÃO', '1718053100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transferências Diretas do FNDE referentes ao Programa Nacional de Apoio ao Transporte do Escolar - PNATE - Principal' AS 'DESCRIÇÃO', '1718054100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Educação' AS 'TIPO', 'Transferências do Salário-Educação- Principal' AS 'DESCRIÇÃO', '1718051100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ICMS' AS 'TIPO', 'Cota-Parte do ICMS - Principal' AS 'DESCRIÇÃO', '1728011100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ICMS' AS 'TIPO', 'Transferência Financeira do ICMS –Desoneração – L.C. Nº 87/96 - Princ' AS 'DESCRIÇÃO', '1718061100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPI/IR' AS 'TIPO', 'Cota-Parte do Fundo de Participação dos Municípios - Cota Mensal - Pri' AS 'DESCRIÇÃO', '1718012100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPI/IR' AS 'TIPO', 'Cota-Parte do IPI - Municípios - Principal' AS 'DESCRIÇÃO', '1728013100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPI/IR' AS 'TIPO', 'Imposto sobre a Renda - Retido na Fonte - Outros Rendimentos - Princip' AS 'DESCRIÇÃO', '1113034102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPI/IR' AS 'TIPO', 'Imposto sobre a Renda de Pessoa Física - IRPF - Principal' AS 'DESCRIÇÃO', '1113011100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPI/IR' AS 'TIPO', 'Imposto sobre a Renda de Pessoa Jurídica - IRPJ - Líquida de Incentivo' AS 'DESCRIÇÃO', '1113021100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPTU' AS 'TIPO', 'Imposto sobre a Propriedade Predial e Territorial Urbana - Multas e Ju' AS 'DESCRIÇÃO', '1118011200' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPTU' AS 'TIPO', 'Imposto sobre a Propriedade Predial e Territorial Urbana - Principal' AS 'DESCRIÇÃO', '1118011100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'IPVA' AS 'TIPO', 'Cota-Parte do IPVA - Principal' AS 'DESCRIÇÃO', '1728012100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ISS' AS 'TIPO', 'ISS - CONSTRUÇÃO CIVIL' AS 'DESCRIÇÃO', '1118023103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ISS' AS 'TIPO', 'ISS - PROFISSIONAIS LIBERAIS' AS 'DESCRIÇÃO', '1118023104' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ISS' AS 'TIPO', 'ISS - SIMPLES NACIONAL' AS 'DESCRIÇÃO', '1118023102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ISS' AS 'TIPO', 'ISS QUALQUER NATUREZA' AS 'DESCRIÇÃO', '1118023101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ITBI' AS 'TIPO', 'Imposto sobre Transmissão “Inter Vivos” de Bens Imóveis e de Direitos' AS 'DESCRIÇÃO', '1118014100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'ITR' AS 'TIPO', 'Cota-Parte do Imposto Sobre a Propriedade Territorial Rural - Principa' AS 'DESCRIÇÃO', '1718015100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Alienação de Bens Imóveis - Alienação - Principal' AS 'DESCRIÇÃO', '2220001101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Aluguéis e Arrendamentos - Principal' AS 'DESCRIÇÃO', '1310011100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Aportes Periódicos para Amortização de Déficit Atuarial do RPPS - Prin' AS 'DESCRIÇÃO', '1990011100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Compensações Financeiras entre o Regime Geral e os Regimes Próprios de' AS 'DESCRIÇÃO', '1990031101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Cota-Parte da Contribuição de Intervenção no Domínio Econômico - Principal' AS 'DESCRIÇÃO', '1728014100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Demais Receitas Patrimoniais - Principal' AS 'DESCRIÇÃO', '1390001100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'FEX - AUXÍLIO FINANCEIRO PARAFOMENTO A EXPORTAÇÃO' AS 'DESCRIÇÃO', '1718991102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'FOROS' AS 'DESCRIÇÃO', '1310012101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Ganho com a Alienação de Outros Bens Móveis - Principal' AS 'DESCRIÇÃO', '2213001112' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'LAUDÊMIOS' AS 'DESCRIÇÃO', '1310012102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Multas e Juros Previstos em Contratos - Principal' AS 'DESCRIÇÃO', '1910091100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'MULTAS PREVISTAS EM LEGISLAÇÃODE TRANSITO' AS 'DESCRIÇÃO', '1910011103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Outras Receitas' AS 'DESCRIÇÃO', '1990990400' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Outras Receitas Correntes - Principal' AS 'DESCRIÇÃO', '1990991100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'OUTRAS RECEITAS DIVERSAS PMI' AS 'DESCRIÇÃO', '1990990500' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'OUTRAS RECEITAS DO FEAPGMI' AS 'DESCRIÇÃO', '1990990600' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Outras Restituições' AS 'DESCRIÇÃO', '1922990200' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Outras Restituições - Não Especificadas Anteriormente - Principal' AS 'DESCRIÇÃO', '1928029100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Outras Restituições - Principal' AS 'DESCRIÇÃO', '1922991100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Outros Serviços - Principal' AS 'DESCRIÇÃO', '1690991100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'PROGRAMA DE FINANCIAMENTO - CEF/FINISA' AS 'DESCRIÇÃO', '2119001101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'RECEITA DE HONORÁRIOSCOBRANÇA ADMINISTRATIVA' AS 'DESCRIÇÃO', '1990122102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'RECEITA DE HONORÁRIOSCOBRANÇA JUDICIAL' AS 'DESCRIÇÃO', '1990122101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Receita de Ônus de Sucumbência' AS 'DESCRIÇÃO', '1990122103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'RECEITAS AUTO DE INFRAÇÃO- MEIO AMBIENTE' AS 'DESCRIÇÃO', '1910011102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'RECEITAS AUTO INFRAÇÃO- SEMFA' AS 'DESCRIÇÃO', '1910011101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS - FONTE 49' AS 'DESCRIÇÃO', '1321001154' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS - FONTE 50' AS 'DESCRIÇÃO', '1321001155' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Remuneração de Depósitos Bancários - FONTE 52' AS 'DESCRIÇÃO', '1321001156' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIOS FONTE 01 - FMAGRO' AS 'DESCRIÇÃO', '1321001125' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCARIOS FONTE 01 - FMMA' AS 'DESCRIÇÃO', '1321001124' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS FONTE 26 - ALIENAÇÃO DOS BENS' AS 'DESCRIÇÃO', '1321001153' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS FONTE 45 - CESSÃO ONEROSA  LEI 13.885/19' AS 'DESCRIÇÃO', '1321001149' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 01 - FMAS' AS 'DESCRIÇÃO', '1321001146' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 01 - FMT' AS 'DESCRIÇÃO', '1321001150' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPOSITOS BANCÁRIOSFONTE 03 - FMT' AS 'DESCRIÇÃO', '1321001127' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 08 - FMDEL' AS 'DESCRIÇÃO', '1321001129' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 21 - CIDE' AS 'DESCRIÇÃO', '1321001114' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 22 - COSIP' AS 'DESCRIÇÃO', '1321001140' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 37 - F.E. PGM' AS 'DESCRIÇÃO', '1321001133' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO INVESTIMENTOS RENDAFIXA' AS 'DESCRIÇÃO', '1321004101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERAÇÃO INVESTIMENTOS RENDAVARIÁVEL' AS 'DESCRIÇÃO', '1321004102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'REMUNERÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 01 - TESOURO' AS 'DESCRIÇÃO', '1321001123' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Ressarcimento de Custos - Principal' AS 'DESCRIÇÃO', '1923021100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Ressarcimento de Custos Operacionais do Ente - Inciso III, Art.11 do Decreto nº90/2019' AS 'DESCRIÇÃO', '1923991101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'RESSARCIMENTO DE DESPESA DE PESSOALCEDIDO' AS 'DESCRIÇÃO', '1922990300' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Restituição de Benefícios Não Desembolsados - Principal' AS 'DESCRIÇÃO', '1922021100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Restituição de Despesas de Exercícios Anteriores - Principal' AS 'DESCRIÇÃO', '1922061100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'RESTITUIÇÕES DO AUXILIO-TRANSPORTES' AS 'DESCRIÇÃO', '1922990100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Outros' AS 'TIPO', 'Serviços Administrativos e Comerciais Gerais - Serviços Administrativo' AS 'DESCRIÇÃO', '1610011127' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota Parte Royalties(Lei n.º 7.990/89) Vinc.à Saúde - Compensação Financeira pela Produção de Petróleo - Lei n.º 12.858/13 -  - Principal' AS 'DESCRIÇÃO', '1718991108' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota Parte Royalties(Lei n.º 7.990/89)-Vinc.à Educação - Compensação Financeira pela Produção de Petróleo - Lei n.º 12.858/13 - Principal' AS 'DESCRIÇÃO', '1718991107' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota Parte Royalties(Lei n.º 9.478/97) Vinc.à Saúde- Compensação Financeira pela Produção de Petróleo - Lei n.º 12.858/13 -  - Principal' AS 'DESCRIÇÃO', '1718991110' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota Parte Royalties(Lei n.º 9.478/97)-Vinc.à Educação - Compensação Financeira pela Produção de Petróleo - Lei n.º 12.858/13 - Principal' AS 'DESCRIÇÃO', '1718991109' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota-parte da Compensação Financeira de Recursos Minerais - CFEM - Pri' AS 'DESCRIÇÃO', '1718022100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota-Parte do Fundo Especial do Petróleo – FEP - Principal' AS 'DESCRIÇÃO', '1718026100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota-parte Royalties – CompensaçãoFinanceira pela Produção de Petróle' AS 'DESCRIÇÃO', '1718023100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota-parte Royalties – CompensaçãoFinanceira pela Produção do Petróle' AS 'DESCRIÇÃO', '1728023100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'Cota-parte Royalties pela Participação Especial – Lei nº 9.478/97, art' AS 'DESCRIÇÃO', '1718025100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS FONTE 42 - ROYALTIES LEI 12.858/13 EDUCAÇÃO' AS 'DESCRIÇÃO', '1321001148' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOS FONTE 44 - ROYALTIES LEI 12.858/13 SAÚDE' AS 'DESCRIÇÃO', '1321001147' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 13 - ROYALTIES' AS 'DESCRIÇÃO', '1321001101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'Royalties' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 14 - ROYALTIES' AS 'DESCRIÇÃO', '1321001102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'AGENTE COMUNITÁRIO DE SAÚDE' AS 'DESCRIÇÃO', '1718031004' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLAFB - ASSISTÊNCIA FARMACÊUTICA BÁSICA' AS 'DESCRIÇÃO', '1718034001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLAFB - OUTROS REPASSES ASSITÊNCIAFARMACÊUTICA' AS 'DESCRIÇÃO', '1718034002' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLGES - IMPLANTAÇÃO AÇÕES E SERVIÇOS DE SAÚDE' AS 'DESCRIÇÃO', '1718035001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLGES - OUTROS REPASSES GESTÃO SUS' AS 'DESCRIÇÃO', '1718035002' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLINVEST - ATENÇÃO BÁSICA' AS 'DESCRIÇÃO', '2418041001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLINVEST - ATENÇÃO ESPECIALIZADA' AS 'DESCRIÇÃO', '2418042001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLINVEST - OUTROS REPASSES DO BLOCO DE INVESTIMENTOS' AS 'DESCRIÇÃO', '2418049002' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLINVEST - VIGILÂNCIA EM SAÚDE' AS 'DESCRIÇÃO', '2418043001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLMAC - FAEC - OUTRAS' AS 'DESCRIÇÃO', '1718032004' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLMAC - FAEC - TERAPIA RENAL SUBSTITUTIVA (NEFROLOGIA)' AS 'DESCRIÇÃO', '1718032003' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLMAC - OUTROS REPASSES MAC' AS 'DESCRIÇÃO', '1718032006' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLMAC - SAMU - SERVIÇO ATENDIMENTOMÓVEL URGÊNCIA' AS 'DESCRIÇÃO', '1718032002' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLMAC - TETO GESTÃO PLENA - MAC' AS 'DESCRIÇÃO', '1718032001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLVGS - ACE - ASSISTÊNCIA FINANCEIRA COMPLEMENTAR AO MUNICÍPIO' AS 'DESCRIÇÃO', '1718033004' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLVGS - INCENTIVO FINANCEIRO AO MUNICÍPIO VIGILÂNCIA SAÚDE' AS 'DESCRIÇÃO', '1718033001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLVGS - IPVS - INCENTIVOS PONTUAISAÇÕES VIGILÂNCIA SAÚDE' AS 'DESCRIÇÃO', '1718033002' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLVGS - OUTROS REPASSES VIGILÂNCIASANITÁRIA EM SAÚDE' AS 'DESCRIÇÃO', '1718033006' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLVGS - PVVS- AÇÕES PREV. CONT. DAS DST/AIDS E HEPATITES VIRAIS' AS 'DESCRIÇÃO', '1718033003' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'BLVGS - VIGILÂNCIA SANITÁRIA' AS 'DESCRIÇÃO', '1718033005' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'CO - FINANCIAMENTO DA ATENÇÃO ESPECIALIZADA' AS 'DESCRIÇÃO', '1728031103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'CO-FINANCIAMENTO DA ATENÇÃO PRIMÁRIA' AS 'DESCRIÇÃO', '1728031102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'CONTRAPARTIDA ASSISTENCIA FARMACEUTICA' AS 'DESCRIÇÃO', '1728031101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'INCENTIVO AÇÕES ESTRATÉGICAS' AS 'DESCRIÇÃO', '1718031003' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'INCENTIVO FINANCEIRO DA APS - CAPT. PONDERADA' AS 'DESCRIÇÃO', '1718031001' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'INCENTIVO FINANCEIRO DA APS - DESEMP.' AS 'DESCRIÇÃO', '1718031002' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'INCENTIVO FINANCEIRO DA APS - P/CAPTA TRANSIÇÃO' AS 'DESCRIÇÃO', '1718031005' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'INCREMENTO TEMPORÁRIO AO CUSTEIO SERVIÇOS ASSISTÊNCIA HOSPITALAR E AMBU' AS 'DESCRIÇÃO', '1718032005' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'INCREMENTO TEMPORARIO AO CUSTEIO SERVIÇOS DA ATENÇÃO PRIMÁRIA' AS 'DESCRIÇÃO', '1718031006' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'OUTROS PROGRAMAS DA ATENÇÃO PRIMÁRIA' AS 'DESCRIÇÃO', '1718031007' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'OUTROS REPASSES DO ESTADO' AS 'DESCRIÇÃO', '1728031109' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'PROGRAMA / PRIMEIRA INFANCIA NO SUAS' AS 'DESCRIÇÃO', '1718041116' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'PROGRAMA / PRIMEIRA INFANCIA NO SUAS' AS 'DESCRIÇÃO', '1718121016' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 05 - SUS' AS 'DESCRIÇÃO', '1321001112' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 12 - TESOURO VINC SAÚDE' AS 'DESCRIÇÃO', '1321001111' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 25 - FEAS/PES' AS 'DESCRIÇÃO', '1321001135' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 28 - FES' AS 'DESCRIÇÃO', '1321001107' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'REMUNERAÇÃO DE DEPÓSITOS BANCÁRIOSFONTE 30 - INVESTIMENTOS SUS' AS 'DESCRIÇÃO', '1321001109' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'SAMU - SERVIÇO DE ATENDIMENTO MÓVEL DE URGÊNCIA' AS 'DESCRIÇÃO', '1728031104' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'SAÚDE MENTAL' AS 'DESCRIÇÃO', '1728031106' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'TRANSF. FES / PROGRAMA NASCER CIDADÃO / REDE CEGONHA' AS 'DESCRIÇÃO', '1728031110' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'SAUDE' AS 'TIPO', 'VIGILÂNCIA EM SAÚDE' AS 'DESCRIÇÃO', '1728031105' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Outras Taxas pela Prestação de Serviços - Principal' AS 'DESCRIÇÃO', '1122011110' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxa de Controle e Fiscalização Ambiental - Principal' AS 'DESCRIÇÃO', '1121041100' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'TAXA DE PUBLICIDADE COMERCIAL' AS 'DESCRIÇÃO', '1121260000' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização - Autorização de Funcioname' AS 'DESCRIÇÃO', '1121011107' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização - Funcionamento de Estabele' AS 'DESCRIÇÃO', '1121011106' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização - Outras Taxas pelo Poder d' AS 'DESCRIÇÃO', '1121011118' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização - Utilização de Área de Dom' AS 'DESCRIÇÃO', '1121011108' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização de Engenhos de Publicidade' AS 'DESCRIÇÃO', '1121011102' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização de Localização e Funcioname' AS 'DESCRIÇÃO', '1121011101' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização de Obras Particulares - Pri' AS 'DESCRIÇÃO', '1121011103' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas de Inspeção, Controle e Fiscalização de Vigilância Sanitária (Sa' AS 'DESCRIÇÃO', '1121011109' AS 'CÓDIGO ORÇAMENTÁRIO' UNION ALL
SELECT 'TAXAS' AS 'TIPO', 'Taxas pela Prestação de Serviços de Coleta de Resíduos Sólidos - Princ' AS 'DESCRIÇÃO', '1122011101' AS 'CÓDIGO ORÇAMENTÁRIO'
