SELECT '0' AS 'CODIGO', 'FONTE ORDINARIA' AS 'DESCRIÇÃO' UNION ALL
SELECT '1' AS 'CODIGO', 'TESOURO MUNICIPAL' AS 'DESCRIÇÃO' UNION ALL
SELECT '2' AS 'CODIGO', 'FUNDEF' AS 'DESCRIÇÃO' UNION ALL
SELECT '3' AS 'CODIGO', 'RECURSOS DE MULTAS DE TRANSITO' AS 'DESCRIÇÃO' UNION ALL
SELECT '4' AS 'CODIGO', 'CONVÊNIOS' AS 'DESCRIÇÃO' UNION ALL
SELECT '5' AS 'CODIGO', 'SUS - BLOCO CUSTEIO' AS 'DESCRIÇÃO' UNION ALL
SELECT '6' AS 'CODIGO', 'RECURSOS DO RPPS' AS 'DESCRIÇÃO' UNION ALL
SELECT '7' AS 'CODIGO', 'SALÁRIO-EDUCAÇÃO' AS 'DESCRIÇÃO' UNION ALL
SELECT '8' AS 'CODIGO', 'RECURSOS DO FUMDEL' AS 'DESCRIÇÃO' UNION ALL
SELECT '9' AS 'CODIGO', 'FUNDEB - VALORIZAÇÃO DO MAGISTÉRIO' AS 'DESCRIÇÃO' UNION ALL
SELECT '10' AS 'CODIGO', 'FUNDEB - MANUTENÇÃO E DESENVOLVIMENTO' AS 'DESCRIÇÃO' UNION ALL
SELECT '11' AS 'CODIGO', 'TESOURO MUNCIPAL DESTINADO A EDUCAÇÃO' AS 'DESCRIÇÃO' UNION ALL
SELECT '12' AS 'CODIGO', 'TESOURO MUNICIPAL DESTINADO A SAÚDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '13' AS 'CODIGO', 'ROYALTIES - LEI 7990/89' AS 'DESCRIÇÃO' UNION ALL
SELECT '14' AS 'CODIGO', 'ROYALTIES - LEI 9478/97' AS 'DESCRIÇÃO' UNION ALL
SELECT '15' AS 'CODIGO', 'TRANSFERENCIAS DO PNAE - FNDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '16' AS 'CODIGO', 'TRANSEFERENCIAS DO PNATE - FNDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '17' AS 'CODIGO', 'CONVÊNIOS VINCULADOS A EDUCAÇÃO' AS 'DESCRIÇÃO' UNION ALL
SELECT '18' AS 'CODIGO', 'CONVÊNIOS VINCULADOS A SAÚDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '19' AS 'CODIGO', 'TRANSFERENCIAS DO FNAS' AS 'DESCRIÇÃO' UNION ALL
SELECT '20' AS 'CODIGO', 'RECURSOS DO FMCA' AS 'DESCRIÇÃO' UNION ALL
SELECT '21' AS 'CODIGO', 'CIDE - CONTRIBUIÇÃO DOMÍNIO ECONÔMICO' AS 'DESCRIÇÃO' UNION ALL
SELECT '22' AS 'CODIGO', 'COSIP - CONTR. SERV. ILUMINAÇÃO PÚBLICA' AS 'DESCRIÇÃO' UNION ALL
SELECT '23' AS 'CODIGO', 'TRANSFERENCIAS DO PDDE - FNDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '24' AS 'CODIGO', 'OUTRAS TRANSF. RECURSOS FNDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '25' AS 'CODIGO', 'TRANSFERENCIAS DO FEAS' AS 'DESCRIÇÃO' UNION ALL
SELECT '26' AS 'CODIGO', 'RECUSROS DE ALIENAÇÃO DOS BENS' AS 'DESCRIÇÃO' UNION ALL
SELECT '27' AS 'CODIGO', 'SUS - ATENÇÃO BÁSICA' AS 'DESCRIÇÃO' UNION ALL
SELECT '28' AS 'CODIGO', 'TRANSF. RECURSOS ESTADO - FES' AS 'DESCRIÇÃO' UNION ALL
SELECT '29' AS 'CODIGO', 'SUS - ASSISTÊNCIA FARMACEUTICA' AS 'DESCRIÇÃO' UNION ALL
SELECT '30' AS 'CODIGO', 'SUS - BLOCO INVESTIMENTOS' AS 'DESCRIÇÃO' UNION ALL
SELECT '31' AS 'CODIGO', 'SUS - GESTÃO SUS' AS 'DESCRIÇÃO' UNION ALL
SELECT '32' AS 'CODIGO', 'SUS VIGILÂNCIA EM SAÚDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '33' AS 'CODIGO', 'OUTRAS TRANSF. RECUROS SUS' AS 'DESCRIÇÃO' UNION ALL
SELECT '34' AS 'CODIGO', 'RECURSOS ALIENAÇÃO BENS DESTINADOS SAÚDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '35' AS 'CODIGO', 'RECURSOS ALIENAÇÃO BENS DEST. EDUCAÇÃO' AS 'DESCRIÇÃO' UNION ALL
SELECT '36' AS 'CODIGO', 'CONVENIO - PADEM' AS 'DESCRIÇÃO' UNION ALL
SELECT '37' AS 'CODIGO', 'RECURSOS DO FEAPGMI' AS 'DESCRIÇÃO' UNION ALL
SELECT '38' AS 'CODIGO', 'RECURSOS DA CDI' AS 'DESCRIÇÃO' UNION ALL
SELECT '39' AS 'CODIGO', 'ARRECADAÇÃO SAAE' AS 'DESCRIÇÃO' UNION ALL
SELECT '40' AS 'CODIGO', 'RECURSOS DO FEGESPI' AS 'DESCRIÇÃO' UNION ALL
SELECT '41' AS 'CODIGO', 'RECEITA DESVINCULADA - EC 93/16 DM 74/18' AS 'DESCRIÇÃO' UNION ALL
SELECT '42' AS 'CODIGO', 'ROYALTIES - LEI 12858/13 - EDUCAÇÃO' AS 'DESCRIÇÃO' UNION ALL
SELECT '43' AS 'CODIGO', 'RECURSOS RPPS/ASSISTÊNCIA MÉDICA' AS 'DESCRIÇÃO' UNION ALL
SELECT '44' AS 'CODIGO', 'ROYALTIES - LEI 12.858/13 - SAÚDE' AS 'DESCRIÇÃO' UNION ALL
SELECT '45' AS 'CODIGO', 'CESSÃO ONEROSA - LEI 13.885/19' AS 'DESCRIÇÃO' UNION ALL
SELECT '46' AS 'CODIGO', 'SUS - COVID-19' AS 'DESCRIÇÃO' UNION ALL
SELECT '47' AS 'CODIGO', 'FES - COVID-19' AS 'DESCRIÇÃO' UNION ALL
SELECT '48' AS 'CODIGO', 'FNAS - COVID - 19' AS 'DESCRIÇÃO' UNION ALL
SELECT '49' AS 'CODIGO', 'FNC/LEI ALDIR BLANC' AS 'DESCRIÇÃO' UNION ALL
SELECT '50' AS 'CODIGO', 'RECURSOS COVID - 19 (INCISO I, LC173-20)' AS 'DESCRIÇÃO' UNION ALL
SELECT '51' AS 'CODIGO', 'SUS - COVID-19 (INVESTIMENTOS)' AS 'DESCRIÇÃO' UNION ALL
SELECT '52' AS 'CODIGO', 'RECURSOS DE OP. CRÉDITO - FINISA' AS 'DESCRIÇÃO' UNION ALL
SELECT '53' AS 'CODIGO', 'RECURSOS DE OP. DE CRÉDITO - PMAT' AS 'DESCRIÇÃO' UNION ALL
SELECT '54' AS 'CODIGO', 'RECURSOS DE OP. DE CRÉDITO - PNAFM' AS 'DESCRIÇÃO' UNION ALL
SELECT '55' AS 'CODIGO', 'FUNDEB - COMPLEMENTAÇÃO VAAF (70%)' AS 'DESCRIÇÃO' UNION ALL
SELECT '56' AS 'CODIGO', 'FUNDEB - COMPLEMENTAÇÃO VAAF (30%)' AS 'DESCRIÇÃO' UNION ALL
SELECT '57' AS 'CODIGO', 'FUNDEB - COMPLEMENTAÇÃO VAAT (70%)' AS 'DESCRIÇÃO' UNION ALL
SELECT '58' AS 'CODIGO', 'FUNDEB - COMPLEMENTAÇÃO VAAT (30%)' AS 'DESCRIÇÃO' UNION ALL
SELECT '142' AS 'CODIGO', 'COVID' AS 'DESCRIÇÃO'
